In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2963, 5159, 2120, 742],
 [2963, 5159, 2120, 6250],
 [2963, 8570, 2120, 331],
 [8771, 7677, 6967, 8939, 77],
 [8771, 7677, 6967, 8939, 9947],
 [6917, 2963, 1951, 2120, 4370],
 [831, 89, 7794, 8939]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2963 5159 2120  742]
 [   0    0    0    0 2963 5159 2120 6250]
 [   0    0    0    0 2963 8570 2120  331]
 [   0    0    0 8771 7677 6967 8939   77]
 [   0    0    0 8771 7677 6967 8939 9947]
 [   0    0    0 6917 2963 1951 2120 4370]
 [   0    0    0    0  831   89 7794 8939]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Karti\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 460ms/step


array([[[ 4.11567204e-02, -4.60257530e-02,  2.89566442e-03,
          2.01389305e-02, -3.73832583e-02, -2.99036391e-02,
         -1.20422952e-02,  1.14915259e-02, -4.99167107e-02,
          4.46859263e-02],
        [ 4.11567204e-02, -4.60257530e-02,  2.89566442e-03,
          2.01389305e-02, -3.73832583e-02, -2.99036391e-02,
         -1.20422952e-02,  1.14915259e-02, -4.99167107e-02,
          4.46859263e-02],
        [ 4.11567204e-02, -4.60257530e-02,  2.89566442e-03,
          2.01389305e-02, -3.73832583e-02, -2.99036391e-02,
         -1.20422952e-02,  1.14915259e-02, -4.99167107e-02,
          4.46859263e-02],
        [ 4.11567204e-02, -4.60257530e-02,  2.89566442e-03,
          2.01389305e-02, -3.73832583e-02, -2.99036391e-02,
         -1.20422952e-02,  1.14915259e-02, -4.99167107e-02,
          4.46859263e-02],
        [ 3.48156355e-02,  2.13829614e-02, -1.47022828e-02,
          4.17763479e-02,  1.06608272e-02, -2.36496814e-02,
          3.85040380e-02, -7.65245035e-03, -2.808228

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 2963, 5159, 2120,  742], dtype=int32)